Repository Rubensrvsc/atividade-2-cesar, pull requests merged in 2022-11, with the labels that each got.

#1 Feat comments
  Gemfile.lock
  app/controllers/comments_controller.rb
  app/helpers/comments_helper.rb
  app/models/comment.rb
  app/views/comments/_comment.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/edit.html.erb
  app/views/comments/index.html.erb
  app/views/comments/new.html.erb
  app/views/comments/show.html.erb
  config/routes.rb
  db/migrate/20221119194502_create_comments.rb
  db/schema.rb
  test/controllers/comments_controller_test.rb
  test/fixtures/comments.yml
  test/models/comment_test.rb
Labels: documentation, good first issue

#2 Feat logs
  app/controllers/comments_controller.rb
  app/controllers/logs_controller.rb
  app/helpers/logs_helper.rb
  app/models/comment.rb
  app/models/log.rb
  app/views/logs/index.html.erb
  config/routes.rb
  db/migrate/20221119223743_create_logs.rb
  db/schema.rb
  test/controllers/logs_controller_test.rb
  test/fixtures/logs.yml
  test/models/log_test.rb
Labels: documentation, help wanted

#3 Feat actors movies relationship
  app/controllers/actors_controller.rb
  app/controllers/movies_controller.rb
  app/helpers/actors_helper.rb
  app/helpers/movies_helper.rb
  app/models/actor.rb
  app/models/actors_movie.rb
  app/models/movie.rb
  app/views/actors/_actor.html.erb
  app/views/actors/_actor.json.jbuilder
  app/views/actors/_form.html.erb
  app/views/actors/edit.html.erb
  app/views/actors/index.html.erb
  app/views/actors/index.json.jbuilder
  app/views/actors/new.html.erb
  app/views/actors/show.html.erb
  app/views/actors/show.json.jbuilder
  app/views/movies/_form.html.erb
  app/views/movies/_movie.html.erb
  app/views/movies/_movie.json.jbuilder
  app/views/movies/edit.html.erb
  app/views/movies/index.html.erb
  app/views/movies/index.json.jbuilder
  app/views/movies/new.html.erb
  app/views/movies/show.html.erb
  app/views/movies/show.json.jbuilder
  config/routes.rb
  db/migrate/20221119232718_create_movies.rb
  db/migrate/20221119232918_create_actors.rb
  db/migrate/20221119233639_create_actors_movies.rb
  db/schema.rb
  test/controllers/actors_controller_test.rb
  test/controllers/movies_controller_test.rb
  test/fixtures/actors.yml
  test/fixtures/actors_movies.yml
  test/fixtures/movies.yml
  test/models/actor_test.rb
  test/models/actors_movie_test.rb
  test/models/movie_test.rb
  test/system/actors_test.rb
  test/system/movies_test.rb
Labels: good first issue

#4 Feat movies business
  app/controllers/actors_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/movies_controller.rb
  app/models/actor.rb
  app/models/comment.rb
  app/models/movie.rb
  app/views/actors/_actor.json.jbuilder
  app/views/actors/index.json.jbuilder
  app/views/actors/show.json.jbuilder
  app/views/comments/_form.html.erb
  app/views/layouts/_head.html.erb
  app/views/layouts/application.html.erb
  app/views/movies/_movie.html.erb
  app/views/movies/_movie.json.jbuilder
  app/views/movies/index.json.jbuilder
  app/views/movies/show.json.jbuilder
  config/routes.rb
  db/migrate/20221120134125_add_comment_to_movie.rb
  db/schema.rb
Labels: enhancement, good first issue

#5 Refactor actor relationship
  app/models/actor.rb
  db/schema.rb
Labels: bug, duplicate

#6 refactor: validation from actor required
  app/models/actor.rb
  app/models/movie.rb
Labels: enhancement

#7 Feat seeds
  db/schema.rb
  db/seeds.rb
Labels: good first issue, question

#8 Test application
  .rspec
  Gemfile
  Gemfile.lock
  app/controllers/logs_controller.rb
  bin/rails
  config/routes.rb
  spec/controllers/actors_controller_spec.rb
  spec/controllers/comments_controller_spec.rb
  spec/controllers/logs_controller_spec.rb
  spec/controllers/movies_controller_spec.rb
  spec/models/actor_spec.rb
  spec/models/comment_spec.rb
  spec/models/log_spec.rb
  spec/models/movie_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: enhancement

#9 test: refactor movie controller test
  spec/controllers/movies_controller_spec.rb
Labels: bug
